# Generated by Django 4.1.7 on 2023-03-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('num_frames', models.FloatField()),
                ('bit_rate', models.FloatField()),
                ('fps', models.FloatField()),
                ('size', models.FloatField()),
                ('duration', models.FloatField()),
                ('img_url', models.CharField(max_length=255)),
            ],
        ),
    ]
