# Generated by Django 4.1.7 on 2023-03-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_info',
            name='intro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video_info',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
