# Generated by Django 4.1.7 on 2023-03-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_video_info_intro_video_info_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_info',
            name='bit_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='video_info',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='video_info',
            name='fps',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='video_info',
            name='num_frames',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='video_info',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
