# Generated by Django 4.1.7 on 2023-03-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_alter_video_info_bit_rate_alter_video_info_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_info',
            name='height',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='video_info',
            name='width',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
